version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Pure.Primitives.Bool.Operations"
    - "src/Tests/Pure.Primitives.Bool.Operations.Tests"
  schedule:
    interval: daily
  reviewers:
    - "kudima03"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
    - "kudima03"
